name:                frost
version:             0.0.1.0
synopsis:            Frost
description:         |
  Please see the documentation at <https://github.com/frost-org/frost/blob/master/README.md>
  for usage information
category:            Documentation
github:              "frost-org/frost"
license:             BSD3
author:              "Paweł Szulc"
maintainer:          "paul.szulc@gmail.com"
copyright:           "2019 Paweł Szulc"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/frost#readme>

ghc-options:
- -fplugin=Polysemy.Plugin


default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- polysemy
- polysemy-plugin
- pandoc
- text
- containers
- time
- simple-cmd
- MissingH
- process
- time-compat
- binary-orphans
- binary-instances
- github
- vector
- split

library:
  source-dirs: src

executables:
  frost:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frost

tests:
  frost-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frost
    - QuickCheck
    - hspec
    - raw-strings-qq
